### ISSUE TITLE
fly.io changes

### ISSUE THREAD

**Issue by 96312** [DmitryScaletta/free-heroku-alternatives#2]
Hello, I have zero apps running on the fly.io service and after their latest `flyctl` update - you need to enter a credit card or buy credits to launch an app.  Please update the readme.

**Command line:** 
![image](https://user-images.githubusercontent.com/34262180/187853619-925844b7-7e6b-458b-997f-f593ac6441f2.png)

and my **dashboard:**
![image](https://user-images.githubusercontent.com/34262180/187853355-82f67e6a-6e82-4d9b-a826-728df3fe3cd1.png)

**Comment by DmitryScaletta** [comment]
Thanks for the report.
I just tried to deploy a test app and it really requires a credit card now.
But my app that I deployed before their changes still works fine without a credit card.
I updated info about fly.io in the table.
