### ISSUE TITLE
Railway app free tier update 

### ISSUE THREAD

**Issue by shock-wave007** [DmitryScaletta/free-heroku-alternatives#5]
https://blog.railway.app/p/introducing-trial-hobby-pro-plans

Now it give 5$ trial one time , from aug 01 2023 i guess

**Comment by DmitryScaletta** [comment]
Thanks for the report.

Fixed: https://github.com/DmitryScaletta/free-heroku-alternatives/commit/1ff0afcc589e79265dfeef758eeda8f5b6781fd1

**Comment by shock-wave007** [comment]
iam on free tier and its asking me to click a button every 7 days. i think so. but its not mentioned anywhere on website or docs. if possible look into it. free is myth after heroku killed its free tier

![image](https://github.com/DmitryScaletta/free-heroku-alternatives/assets/29371789/9a3771a2-87bd-4fb4-96e7-ee3f28e2fd29)
![image](https://github.com/DmitryScaletta/free-heroku-alternatives/assets/29371789/388f6b19-ecf0-4de7-8493-4c4e584e6b2f)
